ar_layers: &id001 []
compute_components_flag: false
config_ar: !!python/object:neuralprophet.configure.AR
  ar_layers: *id001
  ar_reg: null
  n_lags: 10
  reg_lambda: null
config_events: null
config_holidays: null
config_lagged_regressors: !!python/object/apply:collections.OrderedDict
- - - selic
    - !!python/object:neuralprophet.configure.LaggedRegressor
      as_scalar: false
      lagged_reg_layers: &id002 []
      n_lags: 10
      normalize: auto
      reg_lambda: null
  - - cambio
    - !!python/object:neuralprophet.configure.LaggedRegressor
      as_scalar: false
      lagged_reg_layers: *id002
      n_lags: 10
      normalize: auto
      reg_lambda: null
  - - prod_petroleo
    - !!python/object:neuralprophet.configure.LaggedRegressor
      as_scalar: false
      lagged_reg_layers: *id002
      n_lags: 10
      normalize: auto
      reg_lambda: null
  - - cotacao_petroleo
    - !!python/object:neuralprophet.configure.LaggedRegressor
      as_scalar: false
      lagged_reg_layers: *id002
      n_lags: 10
      normalize: auto
      reg_lambda: null
config_normalization: !!python/object:neuralprophet.configure.Normalization
  global_data_params: !!python/object/apply:collections.OrderedDict
  - - - ds
      - &id004 !!python/object:neuralprophet.df_utils.ShiftScale
        scale: !!python/object/apply:pandas._libs.tslibs.timedeltas._timedelta_unpickle
        - 868492800000000000
        - 10
        shift: !!python/object/apply:pandas._libs.tslibs.timestamps._unpickle_timestamp
        - 890006400000000000
        - null
        - null
        - 10
    - - y
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: !!python/object/apply:numpy.core.multiarray.scalar
        - &id003 !!python/object/apply:numpy.dtype
          args:
          - f8
          - false
          - true
          state: !!python/tuple
          - 3
          - <
          - null
          - null
          - null
          - -1
          - -1
          - 0
        - !!binary |
          CtejcD0yQkA=
        shift: !!python/object/apply:numpy.core.multiarray.scalar
        - *id003
        - !!binary |
          ZmZmZmZm8T8=
    - - selic
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: !!python/object/apply:numpy.core.multiarray.scalar
        - *id003
        - !!binary |
          AAAAAAAAN0A=
        shift: !!python/object/apply:numpy.core.multiarray.scalar
        - *id003
        - !!binary |
          ZmZmZmZm/j8=
    - - cambio
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: !!python/object/apply:numpy.core.multiarray.scalar
        - *id003
        - !!binary |
          EOm3rwOnEUA=
        shift: !!python/object/apply:numpy.core.multiarray.scalar
        - *id003
        - !!binary |
          iUFg5dAi8j8=
    - - prod_petroleo
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: !!python/object/apply:numpy.core.multiarray.scalar
        - *id003
        - !!binary |
          dY77+rsgpEA=
        shift: !!python/object/apply:numpy.core.multiarray.scalar
        - *id003
        - !!binary |
          vVCPGIGgjUA=
    - - cotacao_petroleo
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: !!python/object/apply:numpy.core.multiarray.scalar
        - *id003
        - !!binary |
          2KNwPQovWkA=
        shift: !!python/object/apply:numpy.core.multiarray.scalar
        - *id003
        - !!binary |
          MzMzMzMzIkA=
  global_normalization: true
  global_time_normalization: true
  local_data_params: !!python/object/apply:collections.OrderedDict
  - - - __df__
      - !!python/object/apply:collections.OrderedDict
        - - - ds
            - *id004
          - - y
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id003
              - !!binary |
                CtejcD0yQkA=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id003
              - !!binary |
                ZmZmZmZm8T8=
          - - selic
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id003
              - !!binary |
                AAAAAAAAN0A=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id003
              - !!binary |
                ZmZmZmZm/j8=
          - - cambio
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id003
              - !!binary |
                EOm3rwOnEUA=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id003
              - !!binary |
                iUFg5dAi8j8=
          - - prod_petroleo
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id003
              - !!binary |
                dY77+rsgpEA=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id003
              - !!binary |
                vVCPGIGgjUA=
          - - cotacao_petroleo
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id003
              - !!binary |
                2KNwPQovWkA=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id003
              - !!binary |
                MzMzMzMzIkA=
  normalize: auto
  unknown_data_normalization: false
config_regressors: !!python/object:neuralprophet.configure.ConfigFutureRegressors
  d_hidden: 4
  model: linear
  num_hidden_layers: 2
  regressors: null
config_seasonality: !!python/object:neuralprophet.configure.ConfigSeasonality
  computation: fourier
  condition_name: null
  daily_arg: false
  daily_global_local: auto
  global_local: global
  mode: additive
  periods: !!python/object/apply:collections.OrderedDict
  - - - yearly
      - !!python/object:neuralprophet.configure.Season
        arg: true
        condition_name: null
        global_local: global
        period: 365.25
        resolution: 6
  reg_lambda: 0
  seasonality_local_reg: false
  weekly_arg: false
  weekly_global_local: auto
  yearly_arg: true
  yearly_global_local: auto
config_train: !!python/object:neuralprophet.configure.Train
  batch_size: 32
  epochs: 60
  lambda_delay: 30
  learning_rate: 0.01
  loss_func: !!python/object:torch.nn.modules.loss.SmoothL1Loss
    _backward_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _backward_pre_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _buffers: {}
    _forward_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _forward_hooks_always_called: !!python/object/apply:collections.OrderedDict
    - []
    _forward_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
    - []
    _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _forward_pre_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
    - []
    _is_full_backward_hook: null
    _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _modules: {}
    _non_persistent_buffers_set: !!set {}
    _parameters: {}
    _state_dict_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
    - []
    beta: 0.3
    reduction: none
    training: true
  loss_func_name: SmoothL1Loss
  lr_finder_args: {}
  n_data: 7171
  newer_samples_start: 0.0
  newer_samples_weight: 2
  optimizer: !!python/name:torch.optim.adamw.AdamW ''
  optimizer_args:
    weight_decay: 0.001
  quantiles:
  - 0.5
  reg_delay_pct: 0.5
  reg_lambda_trend: null
  scheduler: !!python/name:torch.optim.lr_scheduler.OneCycleLR ''
  scheduler_args:
    anneal_strategy: cos
    div_factor: 10.0
    final_div_factor: 10.0
    pct_start: 0.3
    three_phase: true
  trend_reg_threshold: null
config_trend: !!python/object:neuralprophet.configure.Trend
  changepoints: null
  changepoints_range: 0.8
  growth: linear
  n_changepoints: 10
  trend_global_local: global
  trend_local_reg: false
  trend_reg: 0
  trend_reg_threshold: null
id_list:
- __df__
lagged_reg_layers: *id002
max_lags: 10
meta_used_in_model: false
metrics:
  MAE:
  - MeanAbsoluteError
  - {}
  RMSE:
  - MeanSquaredError
  - squared: false
n_forecasts: 1
n_lags: 10
num_seasonalities_modelled: 1
num_seasonalities_modelled_dict: !!python/object/apply:collections.OrderedDict
- - - yearly
    - 1
  - - weekly
    - 1
  - - daily
    - 1
num_trends_modelled: 1
